function(asap, outfile) {
asapfile <- c("# ASAP VERSION 3.0",
"# NYB final model_4 sel_1989",
"#",
"# ASAP GUI 15 AUG 2012",
"#",
"# Number of Years",
asap[[1]]$dat$n_years,
"# First Year",
asap[[1]]$dat$year1,
"# Number of Ages",
asap[[1]]$dat$n_ages,
"# Number of Fleets",
asap[[1]]$dat$n_fleets,
"# Number of Sensitivity Blocks",
asap[[1]]$dat$n_fleet_sel_blocks,
"# Number of Available Survey Indices",
asap[[1]]$dat$n_indices,
"# Natural Mortality",
capture.output(write.table(asap[[1]]$dat$M, sep="\t", row.names=F, col.names=F)),
"# Fecundity Option",
asap[[1]]$dat$fec_opt,
"# Fraction of year that elapses prior to SSB calculation (0=Jan-1)",
asap[[1]]$dat$fracyr_spawn,
"# Maturity",
capture.output(write.table(asap[[1]]$dat$maturity, sep="\t", row.names=F, col.names=F)),
"# Number of Weights at Age Matrices",
asap[[1]]$dat$n_WAA_mats,
"# Weight Matrix - 1",
capture.output(write.table(asap[[1]]$dat$WAA_mats[[1]], sep="\t", row.names=F, col.names=F)),
"# Weight Matrix - 2",
capture.output(write.table(asap[[1]]$dat$WAA_mats[[2]], sep="\t", row.names=F, col.names=F)),
"# Weights at Age Pointers",
asap[[1]]$dat$WAA_pointers,
"# Selectivity Block Assignment",
"# Fleet 1 Selectivity Block Assignment",
asap[[1]]$dat$sel_block_assign[[1]],
"# Selectivity Options for each block 1=by age, 2=logisitic, 3=double logistic",
capture.output(write.table(t(asap[[1]]$dat$sel_block_option), row.names=F, col.names=F)),
"# Selectivity Block #1 Data",
capture.output(write.table(asap[[1]]$dat$sel_ini[[1]], sep="\t", row.names=F, col.names=F)),
"# Selectivity Block #2 Data",
capture.output(write.table(asap[[1]]$dat$sel_ini[[2]], sep="\t", row.names=F, col.names=F)),
"# Selectivity Block #3 Data",
capture.output(write.table(asap[[1]]$dat$sel_ini[[3]], sep="\t", row.names=F, col.names=F)),
"# Selectivity Block #4 Data",
capture.output(write.table(asap[[1]]$dat$sel_ini[[4]], sep="\t", row.names=F, col.names=F)),
"# Selectivity Block #5 Data",
capture.output(write.table(asap[[1]]$dat$sel_ini[[5]], sep="\t", row.names=F, col.names=F)),
"# Fleet Start Age",
asap[[1]]$dat$fleet_sel_start_age,
"# Fleet End Age",
asap[[1]]$dat$fleet_sel_end_age,
"# Age Range for Average F",
capture.output(write.table(t(asap[[1]]$dat$Frep_ages), row.names=F, col.names=F)),
"# Average F report option (1=unweighted, 2=Nweighted, 3=Bweighted)",
asap[[1]]$dat$Frep_type,
"# Use Likelihood constants? (1=yes)",
asap[[1]]$dat$use_like_const,
"# Release Mortality by Fleet",
asap[[1]]$dat$release_mort,
"# Catch Data",
"# Fleet-1 Catch Data",
capture.output(write.table(asap[[1]]$dat$CAA_mats[[1]], sep="\t", row.names=F, col.names=F)),
"# Discards",
"# Fleet-1 Discards Data",
capture.output(write.table(asap[[1]]$dat$DAA_mats[[1]], sep="\t", row.names=F, col.names=F)),
"# Release Proportion",
"# Fleet-1 Release Data",
capture.output(write.table(asap[[1]]$dat$prop_rel_mats[[1]], sep="\t", row.names=F, col.names=F)),
"# Survey Index Data",
"# Aggregate Index Units",
capture.output(write.table(t(asap[[1]]$dat$index_units), row.names=F, col.names=F)),
"# Age Proportion Index Units",
capture.output(write.table(t(asap[[1]]$dat$index_acomp_units), row.names=F, col.names=F)),
"# Weight at Age Matrix",
capture.output(write.table(t(asap[[1]]$dat$index_WAA_pointers), row.names=F, col.names=F)),
"# Index Month",
capture.output(write.table(t(asap[[1]]$dat$index_month), row.names=F, col.names=F)),
"# Index Selectivity Link to Fleet",
capture.output(write.table(t(asap[[1]]$dat$index_sel_choice), row.names=F, col.names=F)),
"# Index Selectivity Options 1=by age, 2=logisitic, 3=double logistic",
capture.output(write.table(t(asap[[1]]$dat$index_sel_option), row.names=F, col.names=F)),
"# Index Start Age",
capture.output(write.table(t(asap[[1]]$dat$index_sel_start_age), row.names=F, col.names=F)),
"# Index End Age",
capture.output(write.table(t(asap[[1]]$dat$index_sel_end_age), row.names=F, col.names=F)),
"# Estimate Proportion (Yes=1)",
capture.output(write.table(t(asap[[1]]$dat$use_index_acomp), row.names=F, col.names=F)),
"# Use Index (Yes=1)",
capture.output(write.table(t(asap[[1]]$dat$use_index), row.names=F, col.names=F)),
"# Index-1 Selectivity Data",
capture.output(write.table(asap[[1]]$dat$index_sel_ini[[1]], sep="\t", row.names=F, col.names=F)),
"# Index-2 Selectivity Data",
capture.output(write.table(asap[[1]]$dat$index_sel_ini[[2]], sep="\t", row.names=F, col.names=F)),
"# Index-3 Selectivity Data",
capture.output(write.table(asap[[1]]$dat$index_sel_ini[[3]], sep="\t", row.names=F, col.names=F)),
"# Index-1 Data",
capture.output(write.table(asap[[1]]$dat$IAA_mats[[1]], sep="\t", row.names=F, col.names=F)),
"# Index-2 Data",
capture.output(write.table(asap[[1]]$dat$IAA_mats[[2]], sep="\t", row.names=F, col.names=F)),
"# Index-3 Data",
capture.output(write.table(asap[[1]]$dat$IAA_mats[[3]], sep="\t", row.names=F, col.names=F)),
"# Phase Control",
"# Phase for F mult in 1st Year",
asap[[1]]$dat$phase_F1,
"# Phase for F mult Deviations",
asap[[1]]$dat$phase_F_devs,
"# Phase for Recruitment Deviations",
asap[[1]]$dat$phase_rec_devs,
"# Phase for N in 1st Year",
asap[[1]]$dat$phase_rec_devs,
"# Phase for Catchability in 1st Year",
asap[[1]]$dat$phase_q,
"# Phase for Catchability Deviations",
asap[[1]]$dat$phase_q_devs,
"# Phase for Stock Recruitment Relationship",
asap[[1]]$dat$phase_SR_scalar,
"# Phase for Steepness",
asap[[1]]$dat$phase_steepness,
"# Recruitment CV by Year",
asap[[1]]$dat$recruit_cv,
"# Lambdas by Index",
capture.output(write.table(t(asap[[1]]$dat$lambda_index), row.names=F, col.names=F)),
"# Lambda for Total Catch in Weight by Fleet",
asap[[1]]$dat$lambda_catch,
"# Lambda for Total Discards at Age by Fleet",
asap[[1]]$dat$lambda_discard,
"# Catch Total CV by Year and Fleet",
asap[[1]]$dat$catch_cv,
"# Discard Total CV by Year and Fleet",
asap[[1]]$dat$discard_cv,
"# Catch Effective Sample Size by Year and Fleet",
asap[[1]]$dat$catch_Neff,
"# Discard Effective Sample Size by Year and Fleet",
asap[[1]]$dat$discard_Neff,
"# Lambda for F Mult in First year by Fleet",
asap[[1]]$dat$lambda_F1,
"# CV for F Mult in First year by Fleet",
asap[[1]]$dat$cv_F1,
"# Lambda for F Mult Deviations by Fleet",
asap[[1]]$dat$lambda_F_devs,
"# CV for F Mult Deviations by Fleet",
asap[[1]]$dat$cv_F_devs,
"# Lambda for N in 1st Year Deviations",
asap[[1]]$dat$lambda_N1_devs,
"# CV for N in 1st Year Deviations",
asap[[1]]$dat$cv_N1_devs,
"# Lambda for Recruitment Deviations",
asap[[1]]$dat$lambda_rec_devs,
"# Lambda for Catchability in First year by Index",
capture.output(write.table(t(asap[[1]]$dat$lambda_q), row.names=F, col.names=F)),
"# CV for Catchability in First year by Index",
capture.output(write.table(t(asap[[1]]$dat$cv_q), row.names=F, col.names=F)),
"# Lambda for Catchability Deviations by Index",
capture.output(write.table(t(asap[[1]]$dat$lambda_q_devs), row.names=F, col.names=F)),
"# CV for Catchability Deviations by Index",
capture.output(write.table(t(asap[[1]]$dat$cv_q_devs), row.names=F, col.names=F)),
"# Lambda for Deviation from Initial Steepness",
asap[[1]]$dat$lambda_steepness,
"# CV for Deviation from Initial Steepness",
asap[[1]]$dat$cv_steepness,
"# Lambda for Deviation from Unexploited Stock Size",
asap[[1]]$dat$lambda_SR_scalar,
"# CV for Deviation from Unexploited Stock Size",
asap[[1]]$dat$cv_SR_scalar,
"# NAA Deviations Flag",
asap[[1]]$dat$N1_flag,
"# Initial Numbers at Age in 1st Year",
capture.output(write.table(t(asap[[1]]$dat$N1_ini), row.names=F, col.names=F)),
"# Initial F Mult in 1st Year by Fleet",
asap[[1]]$dat$F1_ini,
"# Initial Catchabilty by Index",
capture.output(write.table(t(asap[[1]]$dat$q_ini), row.names=F, col.names=F)),
"# Stock Recruitment Flag",
asap[[1]]$dat$SR_scalar_type,
"# Initial Unexploited Stock",
asap[[1]]$dat$SR_scalar_ini,
"# Initial Steepness",
asap[[1]]$dat$steepness_ini,
"# Maximum F",
asap[[1]]$dat$Fmax,
"# Ignore Guesses (Yes=1)",
asap[[1]]$dat$ignore_guesses,
"# Projection Control",
"# Do Projections (Yes=1)",
asap[[1]]$dat$do_proj,
"# Fleet Directed Flag",
asap[[1]]$dat$dir_fleet,
"# Final Year in Projection",
asap[[1]]$dat$nfinalyear,
"# Projection Data by Year",
capture.output(write.table(t(asap[[1]]$dat$proj_ini), row.names=F, col.names=F)),
"# Do MCMC (Yes=1)",
asap[[1]]$dat$doMCMC,
"# MCMC Year Option",
asap[[1]]$dat$MCMC_nyear_opt,
"# MCMC Iterations",
asap[[1]]$dat$MCMC_nboot,
"# MCMC Thinning Factor",
asap[[1]]$dat$MCMC_nthin,
"# MCMC Random Seed",
asap[[1]]$dat$MCMC_nseed,
"# Agepro R Option",
asap[[1]]$dat$fill_R_opt,
"# Agepro R Option Start Year",
asap[[1]]$dat$R_avg_start,
"# Agepro R Option End Year",
asap[[1]]$dat$R_avg_end,
"# Export R Flag",
asap[[1]]$dat$make_R_file,
"# Test Value",
asap[[1]]$dat$testval,
"######",
"###### FINIS ######",
"# Fleet Names",
paste0("#$", asap[[1]]$dat$fleet.names),
"# Survey Names",
paste0("#$",asap[[1]]$index.names[1]),
paste0("#$",asap[[1]]$index.names[2]),
paste0("#$",asap[[1]]$index.names[3]),
"#")
writeLines(asapfile, outfile)
}

#sink("C:/Users/jgorzo/Documents/console_output.txt")
#sink()
